### ISSUE TITLE
module layoutparser has no attribute EfficientDetLayoutModel

### ISSUE THREAD

**Issue by wbb123** [allenai/VILA#18]
Hi! I run the code of VILA PDFPredictor but find the error as follows. Could you please help me with it? Thank!
![Screen Shot 2022-04-26 at 4 58 42 PM](https://user-images.githubusercontent.com/17266152/165411519-e06ade32-1992-4f13-964d-5f8df0a738e0.png)

**Comment by lolipopshock** [comment]
Perhaps you might want to try to upgrade layoutparser to the latest version  -- `pip install -U layoutparser`

**Comment by lolipopshock** [comment]
Alright close it first and feel free to reopen it if you have more questions!
